#!/bin/bash

# Candybean is a next generation automation and testing framework suite.
# It is a collection of components that foster test automation, execution
# configuration, data abstraction, results illustration, tag-based execution,
# top-down and bottom-up batches, mobile variants, test translation across
# languages, plain-language testing, and web service testing.
# Copyright (C) 2013 SugarCRM, Inc. <candybean@sugarcrm.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Purpose: Remove text that causes a fatal parsing error (missing function) in all php files for the ModuleBuilder module.
# Output: Modified php files inside en_dir and for_dir.
# Input: en_dir for_dir
#	 en_dir - directory path containing en_us.lang.php for ModuleBuilder
#	 for_dir - directory path containing foreign language php files for ModuleBuilder
#	 en_dir and for_dir can be the same directory

if [[ $# != 2 || $1 = "-h" || $1 = "-help" || $1 = "--help" ]]
then
	echo "Usage: $0 en_dir for_dir
	en_dir - path to directory that contains en_us.lang.php for ModuleBuilder
	for_dir - path to directory that contains foreign language php files for ModuleBuilder
	en_dir and for_dir can be the same directory"
	exit
fi

if [[ $1 = */ ]]
then
	en_dir=${1%?}
else
	en_dir=$1
fi
en_dir="$en_dir/modules/ModuleBuilder/language"

if [[ $2 = */ ]]
then
	for_dir=${2%?}
else
	for_dir=$2
fi
for_dir="$for_dir/modules/ModuleBuilder/language"

sed -i "s/SugarThemeRegistry::current()->getImage(\"icon_calculated\", '', null, null, \".gif\", \"Calculated Value\")//g" $en_dir/en_us.lang.php
sed -i "s/\.\./\./g" $en_dir/en_us.lang.php

for file in $for_dir/*
do
	sed -i "s/SugarThemeRegistry::current()->getImage(\"icon_calculated\", '', null, null, \".gif\", \"Calculated Value\")//g" $file
	sed -i "s/\.\./\./g" $file
done	
