#!/bin/bash

# Candybean is a next generation automation and testing framework suite.
# It is a collection of components that foster test automation, execution
# configuration, data abstraction, results illustration, tag-based execution,
# top-down and bottom-up batches, mobile variants, test translation across
# languages, plain-language testing, and web service testing.
# Copyright (C) 2013 SugarCRM, Inc. <candybean@sugarcrm.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Purpose: Update a database (create it if necessary) with the provided php files containing key-value pairs. Each key-value pair is a label-to-text mapping for some language. This script merely runs a collection of other scripts. See each of those files for their documentation.
# Output: A database containing tables of language strings that can be used for translations. Each table contains a common label and texts in different languages.
# Input: workspace for_dir sugar_ver db_name
#	  workspace - workspace path of a Jenkins job
#	  for_dir - directory of foreign language php files (Sugar extraction or sugarcrm/translations repository)
#	  sugar_ver - version of Sugar to be downloaded, for example 6_7 or 6_7_1
#	  db_name - name of the database to be updated (or created if necessary), for example Translations_6_7
#	  db_server - database server (centralized server: 10.8.31.10)
#	  db_user - database username (centralized server: translator)
#	  db_pass - database password (centralized server: Sugar123!)

if [ $# != 7 ]
then
	echo "Usage: $0 workspace for_dir sugar_version db_name
	workspace - workspace path of a Jenkins job
	for_dir - directory of foreign language php files (Sugar extraction or sugarcrm/translations repository)
	sugar_version - version of Sugar to be downloaded
	db_name - name of the database to be updated (or created if necessary)		
	db_server - database server (centralized server: 10.8.31.10)
	db_user - database username (centralized server: translator)
	db_pass - database password (centralized server: Sugar123!)"
	exit
fi

if [[ $1 == */ ]]
then
	workspace=${1%?}
else
	workspace=$1
fi

if [[ $2 == */ ]]
then
	for_dir=${2%?}
else
	for_dir=$2
fi

sugar_ver=$3; db_name=$4; db_server=$5; db_user=$6; db_pass=$7

ruby downloadSugar.rb $workspace $sugar_ver

./generateLangsAndModules $workspace/sugar

cd $for_dir/modules/ModuleBuilder/language; rm * 

git ls-files -d | xargs git checkout --

cd ~/git_repos/Voodoo2/src/main/java/com/sugarcrm/voodoo/translations/updatedatabase

./bypassModuleBuilder $workspace/sugar $for_dir

php -f updateDB.php $db_name $workspace/sugar $for_dir $db_server $db_user $db_pass
