#!/bin/bash

if [ $# != 2 ]
then
	echo "Usage: $0 en_string lang
	en_string - string to be translated
	lang - language code (e.g. fr_FR, zh_CN)"
fi

cd ~/git_repos/Voodoo2/src/main/java
javac -d . com/sugarcrm/voodoo/translations/translate_tests/TranslateSingleString.java
java -cp ~/git_repos/Voodoo2/src/test/resources/sample/mysql-connector-java-5.1.18-bin.jar:. com/sugarcrm/voodoo/translations/translate_tests/TranslateSingleString $1 $2
