#!/bin/bash

# Author: Jason Lin (ylin)
# Purpose: 
# Output:
# Input: 1 or 7
# 1 - properties file, 7 - arguments for properties file
# arglist: $output $language $db_name $db_server $db_user $db_pass

if [ $# != 1 -a $# != 7 ]
then
	echo "Usage: $0 1 or 7 arguments please"
	exit
fi

output_subfolder="$output\_$language/`echo $file | rev | cut -d/ -f1 | rev`"

for file in ~/git_repos/SodaIceBox/soda/tests/modules/*
do
	if [ -d $file ]
	then
		# translate.module can be ignored, Translations will iterate through all modules by default
		echo "translate.testpath = $file
		translate.output = $output_subfolder
		translate.language = $language
		translate.database = $db_name
		translate.serverName = $db_server
		translate.username = $db_user
		translate.password = $db_pass
		translate.module = Accounts" > ~/git_repos/Voodoo2/src/test/resources/Translations.properties

		mkdir -p $output_subfolder
		cd ~/git_repos/Voodoo2/src/main/java
		javac -d . com/sugarcrm/voodoo/translations/translate_tests/Translations.java

		java -cp ~/git_repos/Voodoo2/src/test/resources/sample/mysql-connector-java-5.1.18-bin.jar:. com/sugarcrm/voodoo/translations/translate_tests/Translations ~/git_repos/Voodoo2/src/test/resources/Translations.properties
	fi
done
