#!/bin/bash

if [[ $# != 7 || $1 = "-h" || $1 = "-help" || $1 = "--help" ]]
then
        echo "Usage: $0 db_server db_name db_user db_pass input_path output_path mode
Example: ./FindAffectedSodaTests 10.8.31.10 Translations_6_7_latest translator Sugar123! ~/Workspace/SodaIceBox/soda/tests ~/AffectedSodaTests.txt write"
        exit
fi

db_server=$1; db_name=$2; db_user=$3; db_pass=$4; mode=$7

if [[ $5 = */ ]]
then
        input_path=${5%?}
else
        input_path=$5;
fi

if [[ $6 = */ ]]
then
        output_path=${6%?}
else
        output_path=$6
fi

cd ~/Workspace/Voodoo2/src/main/java
javac -d . com/sugarcrm/voodoo/translations/findduplicates/FindAffectedSodaTests.java
java -cp ~/Workspace/Voodoo2/src/test/resources/sample/mysql-connector-java-5.1.18-bin.jar:. com/sugarcrm/voodoo/translations/findduplicates/FindAffectedSodaTests $db_server $db_name $db_user $db_pass $input_path $output_path $mode