#!/bin/bash

# Author: Jason Lin (ylin)
# Purpose: Remove text that causes a missing function error in all php files for the ModuleBuilder module. Without this script, updateDB.php will always halt at ModuleBuilder (fatal parsing error: missing function).
# Output: Modified php files inside en_dir and for_dir.
# Input: en_dir for_dir
#	 en_dir - directory path containing en_us.lang.php for ModuleBuilder
#	 for_dir - direcotry path containing foreign language php files for ModuleBuilder

if [ $# != 2 ]
then
	echo "Usage: $0 en_dir for_dir
	en_dir - path to directory that contains en_us.lang.php for ModuleBuilder
	for_dir - path to directory that contains foreign language php files for ModuleBuilder
	en_dir and for_dir can be the same directory"
	exit
fi

if [[ $1 = */ ]]
then
	en_dir=${1%?}
else
	en_dir=$1
fi
en_dir="$en_dir/modules/ModuleBuilder/language"

if [[ $2 = */ ]]
then
	for_dir=${2%?}
else
	for_dir=$2
fi
for_dir="$for_dir/modules/ModuleBuilder/language"

sed -i "s/SugarThemeRegistry::current()->getImage(\"icon_calculated\", '', null, null, \".gif\", \"Calculated Value\")//g" $en_dir/en_us.lang.php
sed -i "s/\.\./\./g" $en_dir/en_us.lang.php

for file in $for_dir/*
do
	sed -i "s/SugarThemeRegistry::current()->getImage(\"icon_calculated\", '', null, null, \".gif\", \"Calculated Value\")//g" $file
	sed -i "s/\.\./\./g" $file
done	
